

SET(_PROJECT_NAME cereal)

SET(${_PROJECT_NAME}_CMAKE_FLAGS
-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/${_PROJECT_NAME}/install
-DCMAKE_BUILD_TYPE=Release
-DSKIP_PERFORMANCE_COMPARISON=ON
-DBUILD_SANDBOX=OFF
-DBUILD_DOC=OFF
-DBUILD_TESTS=OFF
)

ExternalProject_Add(${_PROJECT_NAME}
PREFIX ${_PROJECT_NAME}
GIT_REPOSITORY    https://github.com/USCiLab/cereal
GIT_TAG           ebef1e929807629befafbb2918ea1a08c7194554
CMAKE_ARGS        ${${_PROJECT_NAME}_CMAKE_FLAGS}
TEST_COMMAND      ""
)

SET(${_PROJECT_NAME}_INCLUDE_DIRS "${CMAKE_BINARY_DIR}/${_PROJECT_NAME}/install/include/")

