

SET(_PROJECT_NAME cvd)

SET(${_PROJECT_NAME}_CMAKE_FLAGS
-DCVD_TooN_INCLUDE_DIR=${toon_SOURCE_DIR}
-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/${_PROJECT_NAME}/install
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
-DCMAKE_BUILD_TYPE=Release
-DCVD_ENABLE_TESTS=OFF
-DCVD_ENABLE_PROGS=OFF
-DCVD_ENABLE_EXAMPLES=OFF
)

ExternalProject_Add(${_PROJECT_NAME}
PREFIX ${_PROJECT_NAME}
GIT_REPOSITORY    https://github.com/edrosten/libcvd
GIT_TAG           b30062150f6a5f105df7d1d8a3899ef96170820e
CMAKE_ARGS        ${${_PROJECT_NAME}_CMAKE_FLAGS}
TEST_COMMAND      ""
)

add_library(${_PROJECT_NAME}_lib STATIC IMPORTED)
set_target_properties(${_PROJECT_NAME}_lib PROPERTIES IMPORTED_LOCATION ${CMAKE_BINARY_DIR}/${_PROJECT_NAME}/install/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}cvd${CMAKE_STATIC_LIBRARY_SUFFIX})

add_dependencies(${_PROJECT_NAME}_lib ${_PROJECT_NAME})

SET(${_PROJECT_NAME}_LIBS "${_PROJECT_NAME}_lib")
SET(${_PROJECT_NAME}_INCLUDE_DIRS "${CMAKE_BINARY_DIR}/${_PROJECT_NAME}/install/include/")

